app/core/routes.py
import os
from datetime import timedelta
from functools import wraps
from twilio.twiml.voice_response import VoiceResponse, Dial
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    flash, abort, make_response, session, Response,
)
from flask_login import login_user, current_user, logout_user, login_required, fresh_login_required
import phonenumbers
from twilio.base.exceptions import TwilioRestException
from app import app, twilio_client
from app.models import *  # TODO optimize
from .forms import *  # TODO optimize
from .utils import clean_args, validate_next_url, verify_tab_request, send_email, transcribe_audio, summarize_audio

core = Blueprint("core", __name__, template_folder="templates")


def track_user(f):
    @wraps(f)
    def decorated_function(*args, **kws):
        response = f(*args, **kws)
        response = make_response(response)

        identifier = request.cookies.get("device_identifier", None)
        device_id = request.cookies.get("device_id", None)

        if device_id:
            device = Device.query.filter_by(alternate_id=device_id).first()
            if device:
                if identifier != device.identifier and identifier is not None:
                    device.identifier = identifier
                    db.session.commit()
            else:
                device = Device()
                db.session.add(device)
                db.session.commit()
                response.set_cookie(
                    "device_id",
                    device.alternate_id,
                    expires=datetime.now(tz=timezone.utc) + timedelta(days=365),
                    httponly=True,
                )
        else:
            device = Device.query.filter_by(identifier=identifier).first()
            if device:
                response.set_cookie(
                    "device_id",
                    device.alternate_id,
                    expires=datetime.now(tz=timezone.utc) + timedelta(days=365),
                    httponly=True,
                )
            else:
                if identifier:
                    device = Device(identifier=identifier)
                    db.session.add(device)
                    db.session.commit()
                    response.set_cookie(
                        "device_id",
                        device.alternate_id,
                        expires=datetime.now(tz=timezone.utc) + timedelta(days=365),
                        httponly=True,
                    )

        return response
    return decorated_function


@app.context_processor
def utility_processor():
    def get_system_setting(name):
        setting_record = SystemSetting.query.filter_by(name=name).first()
        if setting_record is None:
            return False
        else:
            return setting_record.value

    return dict(get_system_setting=get_system_setting)


@app.context_processor
def utility_processor():
    def get_system_setting_time(name):
        setting_record = SystemSetting.query.filter_by(name=name).first()
        if setting_record is None:
            return False
        else:
            return setting_record.last_updated_timestamp

    return dict(get_system_setting_time=get_system_setting_time)


@core.route("/")
@track_user
def index():
    return render_template("index.html")


@core.route("/dashboard")
@track_user
@login_required
def dashboard():
    conversations = Conversation.query.filter(Conversation.users.any(id=current_user.id)).all()
    return render_template("admin/dashboard.html", title="Dashboard", conversations=conversations)


@core.route("/conversations/<alt_id>")
@track_user
@login_required
def conversation(alt_id):
    conversation_record = Conversation.query.filter_by(alternate_id=alt_id).first_or_404()
    if (not current_user.get_role("admin")) and (current_user not in conversation_record.users):
        abort(403)
    if conversation_record.phone_call_id:
        phone_call = PhoneCall.query.get(conversation_record.phone_call_id)
    else:
        phone_call = None
    return render_template("conversation.html", conversation=conversation_record, phone_call=phone_call, title="Conversation")


@core.route("/conversations/<alt_id>/messages", methods=["GET", "POST"])
@track_user
@login_required
def conversation_messages(alt_id):
    conversation_record = Conversation.query.filter_by(alternate_id=alt_id).first_or_404()
    if (not current_user.get_role("admin")) and (current_user not in conversation_record.users):
        abort(403)

    messages = Message.query.filter_by(conversation_id=conversation_record.id).all()
    return render_template("conversation-messages.html", messages=messages)


@core.route("/conversations/<alt_id>/send", methods=["GET", "POST"])
@track_user
@login_required
def conversation_form(alt_id):
    conversation_record = Conversation.query.filter_by(alternate_id=alt_id).first_or_404()
    if (not current_user.get_role("admin")) and (current_user not in conversation_record.users):
        abort(403)

    form = MessageForm()
    if form.validate_on_submit():
        message = Message(
            content=form.message.data,
            user_id=current_user.id,
            conversation_id=conversation_record.id
        )
        db.session.add(message)
        conversation_record.conversation_last_updated_timestamp = datetime.now(tz=timezone.utc)
        db.session.commit()

    return render_template("conversation-form.html", form=form, conversation=conversation_record)


@core.route("/conversations/<alt_id>/notes", methods=["GET", "POST"])
@track_user
@login_required
def conversation_notes(alt_id):
    conversation_record = Conversation.query.filter_by(alternate_id=alt_id).first_or_404()
    if (not current_user.get_role("admin")) and (current_user not in conversation_record.users):
        abort(403)
    note = Note.query.filter_by(conversation_id=conversation_record.id, user_id=current_user.id).first()

    form = NoteForm()
    if form.validate_on_submit():
        if note:
            note.content = form.content.data
        else:
            note = Note(
                content=form.content.data,
                user_id=current_user.id,
                conversation_id=conversation_record.id
            )
            db.session.add(note)
        db.session.commit()

    form.content.data = note.content
    return render_template("conversation-notes.html", form=form, note=note, conversation=conversation_record)


@core.route("/conversations/new", methods=["GET", "POST"])
@track_user
@login_required
def new_conversation():
    form = NewConversationForm()
    if form.validate_on_submit():
        conversation = Conversation()
        db.session.add(conversation)
        db.session.commit()
        for doctor in form.doctors.data:
            doctor_record = User.query.filter_by(alternate_id=doctor).first()
            if doctor_record:
                conversation.users.append(doctor_record)
        patient = User.query.filter_by(alternate_id=form.patient.data).first()
        if patient:
            conversation.users.append(patient)
        else:
            conversation.users.append(current_user)
        db.session.commit()
        for user in conversation.users:
            note = Note(conversation_id=conversation.id, user_id=user.id)
            db.session.add(note)
        db.session.commit()
        flash("Conversation has been created.", "success")
        return redirect(url_for("core.conversation", alt_id=conversation.alternate_id))

    doctors = User.query.join(Role).filter(
        Role.name == "doctor",
        Role.value == True,
        User.active == True,
        User.deleted != True
    ).all()
    form.doctors.choices = [(doctor.alternate_id, doctor.name) for doctor in doctors]

    patients = User.query.join(Role).filter(
        Role.name == "patient",
        Role.value == True,
        User.active == True,
        User.deleted != True
    ).all()
    form.patient.choices = [(patient.alternate_id, patient.name) for patient in patients]
    if current_user.get_role('patient'):
        form.patient.choices = [(current_user.alternate_id, current_user.name)]

    return render_template("new-conversation.html", form=form, title="New Conversation")


@core.route("/incoming-call", methods=["POST"])
def receive_call():
    incoming_call = PhoneCall()
    incoming_call.populate_from_request(request.form)
    db.session.add(incoming_call)
    db.session.commit()
    response = VoiceResponse()
    dial = Dial(
        record="record-from-answer",
        recordingStatusCallback=url_for("core.log_recording"),
    )
    dial.number("+12294123111", statusCallback=url_for("core.update_call_status"))
    response.append(dial)
    return str(response)


@core.route("/log-recording", methods=["POST"])
def log_recording():
    sid = request.form.get("CallSid")
    call = PhoneCall.query.filter_by(call_sid=sid).first()
    if call:
        call.recording_sid = request.form.get("RecordingSid")
        call.recording_url = request.form.get("RecordingUrl")
        call.recording_status = request.form.get("RecordingStatus")
        call.recording_duration = request.form.get("RecordingDuration")
        # Create transcription, conversation, and notes. Add transcription to conversation summary, add AI summary to all notes
        transcription = transcribe_audio(call.recording_url, os.path.join(app.config["UPLOAD_FOLDER"], f"{sid}.wav"))
        summary = summarize_audio(transcription)
        call.transcription = transcription
        conversation_record = Conversation(summary=transcription, phone_call_id=call.id)
        db.session.add(conversation_record)
        db.session.commit()
        doctors = User.query.join(Role).filter(
            Role.name == "doctor",
            Role.value == True,
            User.active == True,
            User.deleted != True
        ).all()
        for doctor in doctors:
            conversation_record.users.append(doctor)

app/core/templates/conversation-form.html
<form hx-post="{{ url_for('core.conversation_form', alt_id=conversation.alternate_id) }}" hx-swap="#form-container">
    {{ form.csrf_token }}

    <div class="mb-3">
        {{ form.message.label(class="form-label") }}
        <div class="relative">
            {{ form.message(class="form-input", id="message", type="text") }}
        </div>
        {% for error in form.message.errors %}
            <p class="form-error">{{ error }}</p>
        {% endfor %}
    </div>

    <div class="flex justify-end">
        {{ form.submit(class='button button-blue') }}
    </div>

</form>

app/core/templates/conversation-notes.html
<form hx-post="{{ url_for('core.conversation_notes', alt_id=conversation.alternate_id) }}" hx-swap="#form-container" hx-trigger="change">
    {{ form.csrf_token }}
    <div class="mb-3">
        <div class="relative">
            {{ form.content(class="form-textarea", id="notes", type="text", rows=10) }}
        </div>
        {% for error in form.content.errors %}
            <p class="form-error">{{ error }}</p>
        {% endfor %}
    </div>
</form>

app/core/templates/conversation.html
{% extends 'admin_base.html' %}
{% block content %}

    <div class="mb-4">
        <h1 class="h1 text-color-dark">Conversation
            <button type="button"
                    class="size-[38px] relative inline-flex justify-center items-center gap-x-2 font-semibold rounded-full border border-transparent text-white hover:bg-white/10 focus:outline-none focus:bg-white/10 disabled:opacity-50 disabled:pointer-events-none"
                    aria-haspopup="dialog" aria-expanded="false"
                    aria-controls="notes-menu"
                    data-hs-overlay="#notes-menu" hx-get="{{ url_for('core.conversation_notes', alt_id=conversation.alternate_id) }}" hx-target="#note-content" hx-trigger="click">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="shrink-0 size-5 text-color-dark" width="24" height="24">
                    <path d="m2.695 14.762-1.262 3.155a.5.5 0 0 0 .65.65l3.155-1.262a4 4 0 0 0 1.343-.886L17.5 5.501a2.121 2.121 0 0 0-3-3L3.58 13.419a4 4 0 0 0-.885 1.343Z" />
                </svg>
                <span class="sr-only">Notes</span>
            </button>
        </h1>
        <p class="body text-color-muted mb-3">{{ conversation.formatted_users }}<br>
            <a href="https://meet.google.com/landing" target="_blank" class="link link-primary">Join Google Meet</a>
        </p>
    </div>
    <div class="admin-content-container mb-2">
        {% if not conversation.phone_call_id %}
            <div class="admin-main-content h-96" id="main-content" hx-get="{{ url_for('core.conversation_messages', alt_id=conversation.alternate_id) }}" hx-trigger="load, every 2s">
            </div>
        {% else %}
            <div class="admin-main-content h-96" id="main-content">
                <h3 class="h3 text-color-dark mb-2">Call Transcription</h3>

                <h3 class="h3-small text-color-dark-2">Call Information</h3>
                <p class="body text-color-muted mb-3">
                    <strong>Call Status:</strong> {{ phone_call.call_status }}<br>
                    <strong>Recording URL:</strong> <a href="{{ phone_call.recording_url }}" target="_blank" class="link link-muted">{{ phone_call.recording_url }}</a><br>
                    <strong>From Number:</strong> {{ phone_call.from_number }}<br>
                    <strong>From City:</strong> {{ phone_call.from_city }}<br>
                    <strong>From State:</strong> {{ phone_call.from_state }}<br>
                    <strong>From Zip:</strong> {{ phone_call.from_zip }}<br>
                    <strong>To Number:</strong> {{ phone_call.to_number }}
                </p>

                <h3 class="h3-small text-color-dark-2">Transcription</h3>
                <p class="body text-color-dark-2">{{ phone_call.transcription }}</p>
            </div>
        {% endif %}
    </div>
    {% if not conversation.phone_call_id %}
        <div class="admin-content-container">
            <div class="admin-main-content" id="form-container">
                <div hx-get="{{ url_for('core.conversation_form', alt_id=conversation.alternate_id) }}" hx-trigger="load" hx-target="#form-container"></div>
            </div>
        </div>
    {% endif %}

    <div id="notes-menu"
         class="hs-overlay hs-overlay-backdrop-open:bg-black/70 hs-overlay-open:translate-x-0 hidden translate-x-full fixed top-0 end-0 transition-all duration-200 transform h-full max-w-xs w-full z-[80] bg-white dark:bg-neutral-800 border-e border-color [--body-scroll:true]"
         role="dialog" tabindex="-1" aria-labelledby="notes-menu-label">
        <div class="flex justify-between items-center py-3 px-4 border-b border-color">
            <h3 id="notes-menu-label" class="h3-small text-color-dark">
                Notes
            </h3>
            <button type="button"
                    class="inline-flex rounded-full p-2 text-color-dark-2 border border-transparent hover:bg-black/10 dark:hover:bg-white/10 focus:outline-none"
                    aria-label="Close" data-hs-overlay="#notes-menu">
                <span class="sr-only">Close</span>
                <svg class="shrink-0 size-5" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                     viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                     stroke-linejoin="round">
                    <path d="M18 6 6 18"></path>
                    <path d="m6 6 12 12"></path>
                </svg>
            </button>
        </div>
        <div class="p-4 body text-color-dark" id="note-content">

        </div>
    </div>

{% endblock %}

app/core/templates/header.html
{% if current_user.is_authenticated %}
    <header class="sticky top-0 inset-x-0 flex flex-wrap md:justify-start md:flex-nowrap z-[48] w-full bg-neutral-800 border-color text-sm py-1.5">
        <nav class="max-w-[85rem] mx-auto w-full flex basis-full items-center px-4">
            <div class="flex-1 flex flex-row justify-end items-center gap-1">
                {% if current_user.get_role('admin') %}
                    <button type="button"
                            class="size-[38px] relative inline-flex justify-center items-center gap-x-2 font-semibold rounded-full border border-transparent text-white hover:bg-white/10 focus:outline-none focus:bg-white/10 disabled:opacity-50 disabled:pointer-events-none"
                            aria-haspopup="dialog" aria-expanded="false"
                            aria-controls="admin-menu"
                            data-hs-overlay="#admin-menu">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"
                             class="shrink-0 size-5" width="24" height="24">
                            <path fill-rule="evenodd"
                                  d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25Zm0 8.625a1.125 1.125 0 1 0 0 2.25 1.125 1.125 0 0 0 0-2.25ZM15.375 12a1.125 1.125 0 1 1 2.25 0 1.125 1.125 0 0 1-2.25 0ZM7.5 10.875a1.125 1.125 0 1 0 0 2.25 1.125 1.125 0 0 0 0-2.25Z"
                                  clip-rule="evenodd"/>
                        </svg>
                        <span class="sr-only">Admin Menu</span>
                    </button>
                {% endif %}
                <div class="mx-2 me-4">
                    <div class="w-px h-4 bg-neutral-500"></div>
                </div>

                <!-- Dropdown -->
                <div class="hs-dropdown [--placement:bottom-right] relative inline-flex">
                    <button id="hs-dropdown-account" type="button"
                            class="size-[38px] inline-flex justify-center items-center gap-x-2 font-semibold rounded-full border border-transparent focus:outline-none disabled:opacity-50 disabled:pointer-events-none dark:text-white"
                            aria-haspopup="menu" aria-expanded="false" aria-label="Dropdown">
                        <img class="shrink-0 size-[38px] rounded-full"
                             src="https://api.dicebear.com/9.x/initials/svg?seed={{ current_user.name }}&radius=50&backgroundColor=00897b,5e35b1,d81b60,3949ab,f4511e,fb8c00&fontSize=46"
                             alt="Avatar">
                    </button>

                    <div class="hs-dropdown-menu transition-[opacity,margin] duration hs-dropdown-open:opacity-100 opacity-0 hidden min-w-60 bg-neutral-800 rounded shadow-md mt-2 border border-color"
                         role="menu" aria-orientation="vertical" aria-labelledby="hs-dropdown-account">
                        <div class="py-3 px-5 bg-neutral-700 text-neutral-200 rounded-t">
                            <p class="text-sm">Signed in as</p>
                            <p class="text-base">{{ current_user.email }}</p>
                        </div>
                        <div class="p-2 space-y-1">
                            <a class="navigation-item-dark"
                               href="{{ url_for('core.settings') }}">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                     stroke-width="1.5" stroke="currentColor" class="shrink-0 size-5" width="24"
                                     height="24">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                          d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.325.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 0 1 1.37.49l1.296 2.247a1.125 1.125 0 0 1-.26 1.431l-1.003.827c-.293.241-.438.613-.43.992a7.723 7.723 0 0 1 0 .255c-.008.378.137.75.43.991l1.004.827c.424.35.534.955.26 1.43l-1.298 2.247a1.125 1.125 0 0 1-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.47 6.47 0 0 1-.22.128c-.331.183-.581.495-.644.869l-.213 1.281c-.09.543-.56.94-1.11.94h-2.594c-.55 0-1.019-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 0 1-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 0 1-1.369-.49l-1.297-2.247a1.125 1.125 0 0 1 .26-1.431l1.004-.827c.292-.24.437-.613.43-.991a6.932 6.932 0 0 1 0-.255c.007-.38-.138-.751-.43-.992l-1.004-.827a1.125 1.125 0 0 1-.26-1.43l1.297-2.247a1.125 1.125 0 0 1 1.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.086.22-.128.332-.183.582-.495.644-.869l.214-1.28Z"/>
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                          d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
                                </svg>
                                Settings
                            </a>
                            <a class="navigation-item-dark"
                               href="{{ url_for('core.logout') }}">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"
                                     class="shrink-0 size-5" width="24" height="24">
                                    <path fill-rule="evenodd"
                                          d="M16.5 3.75a1.5 1.5 0 0 1 1.5 1.5v13.5a1.5 1.5 0 0 1-1.5 1.5h-6a1.5 1.5 0 0 1-1.5-1.5V15a.75.75 0 0 0-1.5 0v3.75a3 3 0 0 0 3 3h6a3 3 0 0 0 3-3V5.25a3 3 0 0 0-3-3h-6a3 3 0 0 0-3 3V9A.75.75 0 1 0 9 9V5.25a1.5 1.5 0 0 1 1.5-1.5h6Zm-5.03 4.72a.75.75 0 0 0 0 1.06l1.72 1.72H2.25a.75.75 0 0 0 0 1.5h10.94l-1.72 1.72a.75.75 0 1 0 1.06 1.06l3-3a.75.75 0 0 0 0-1.06l-3-3a.75.75 0 0 0-1.06 0Z"
                                          clip-rule="evenodd"/>
                                </svg>
                                Logout
                            </a>
                        </div>
                    </div>
                </div>
                <!-- End Dropdown -->
            </div>
        </nav>
    </header>
{% endif %}

<header class="drop-shadow-md flex flex-wrap z-10 lg:justify-start lg:flex-nowrap w-full bg-neutral-800 py-3">
    <nav class="max-w-[85rem] w-full mx-auto px-4 lg:flex lg:items-center lg:justify-between">
        <div class="flex items-center justify-between">
            <a class="flex-none text-xl font-semibold dark:text-white focus:outline-none"
               href="{{ url_for('core.index') }}"
               aria-label="Brand">
                <img class="w-24 h-auto" width="45" height="45" loading="eager"
                     src="{{ url_for('static', filename='images/logo.png') }}"
                     alt="Beacon logo" title="Logo">
            </a>
            <div class="lg:hidden">
                <button type="button"
                        class="hs-collapse-toggle relative flex justify-center items-center gap-x-2 bg-transparent shadow-sm hover:bg-white/10 rounded p-2 focus:outline-none"
                        id="header-navbar-collapse" aria-expanded="false" aria-controls="header-navbar"
                        aria-label="Toggle navigation" data-hs-collapse="#header-navbar">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="white" class="size-6">
                        <path fill-rule="evenodd"
                              d="M2 4.75A.75.75 0 0 1 2.75 4h14.5a.75.75 0 0 1 0 1.5H2.75A.75.75 0 0 1 2 4.75ZM2 10a.75.75 0 0 1 .75-.75h14.5a.75.75 0 0 1 0 1.5H2.75A.75.75 0 0 1 2 10Zm0 5.25a.75.75 0 0 1 .75-.75h14.5a.75.75 0 0 1 0 1.5H2.75a.75.75 0 0 1-.75-.75Z"
                              clip-rule="evenodd"/>
                    </svg>
                    <span class="sr-only">Toggle navigation</span>
                </button>
            </div>
        </div>
        <div id="header-navbar"
             class="hidden hs-collapse overflow-hidden transition-all duration-150 basis-full grow lg:block"
             aria-labelledby="header-navbar-collapse">
            <div class="flex flex-col gap-1 mt-5 lg:flex-row lg:items-center lg:justify-end lg:mt-0 lg:ps-5">
                <a class="header-link" href="{{ url_for('core.index') }}">Home</a>
                {% if current_user.is_authenticated %}
                    <a class="header-link" href="{{ url_for('core.dashboard') }}">Dashboard</a>
                {% endif %}
                {% if current_user.is_anonymous %}
                    <a class="header-link" href="{{ url_for('core.login') }}">Log In</a>
                {% endif %}
            </div>
        </div>
    </nav>
</header>

{% if current_user.is_authenticated %}
    <div id="admin-menu"
         class="hs-overlay hs-overlay-backdrop-open:bg-black/70 hidden size-full fixed top-0 start-0 z-[80] overflow-x-hidden overflow-y-auto pointer-events-none"
         role="dialog" tabindex="-1" aria-labelledby="admin-menu-label">
        <div class="hs-overlay-animation-target hs-overlay-open:scale-100 hs-overlay-open:opacity-100 scale-95 opacity-0 ease-in-out transition-all duration-200 sm:max-w-lg sm:w-full m-3 sm:mx-auto min-h-[calc(100%-3.5rem)]">
            <div class="w-full flex flex-col border border-color rounded pointer-events-auto bg-white dark:bg-neutral-800 shadow">
                <div class="border-b border-color py-3 px-4">
                    <div class="relative">
                        <input class="form-input" id="admin-menu-search" type="text"
                               placeholder="Search for pages..." oninput="filterLinks()" autofocus="">
                    </div>
                </div>
                <script>
                    function filterLinks() {
                        const input = document.getElementById('admin-menu-search').value.toLowerCase();
                        document.querySelectorAll('.admin-menu-option').forEach(link => {
                            const keywords = link.getAttribute('data-keywords').toLowerCase();
                            const keywordList = keywords.split(' ');
                            const match = keywordList.some(keyword =>
                                keyword.includes(input) || levenshtein(keyword, input) <= 2
                            );
                            link.style.display = match ? '' : 'none';
                        });
                    }

                    window.addEventListener("keydown", function (evt) {
                        if (evt.code === "Backslash" && evt.ctrlKey === true) {
                            const overlay = HSOverlay.getInstance('[data-hs-overlay="#admin-menu"]', true);
                            const combobox = HSComboBox.getInstance('#admin-menu [data-hs-combo-box]', true);

                            if (overlay.element && overlay.element.overlay.classList.contains('open')) return false;

                            overlay.element.open();
                            combobox.element.setCurrent();
                        }
                    });
                </script>
                <div class="py-3 px-4 overflow-y-auto">
                    <div class="space-y-1">

                        {% if current_user.get_role('admin') %}
                            <div class="admin-menu-option space-y-0.5" id="users"
                                 data-keywords="users accounts manage">
                                <a class="navigation-item-light"
                                   href="{{ url_for('core.users') }}">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                         stroke-width="1.5" stroke="currentColor" class="shrink-0 size-5" width="24"
                                         height="24">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                              d="M15 19.128a9.38 9.38 0 0 0 2.625.372 9.337 9.337 0 0 0 4.121-.952 4.125 4.125 0 0 0-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 0 1 8.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0 1 11.964-3.07M12 6.375a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0Zm8.25 2.25a2.625 2.625 0 1 1-5.25 0 2.625 2.625 0 0 1 5.25 0Z"/>
                                    </svg>
                                    Users
                                </a>
                            </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}

app/core/templates/index.html
{% extends 'base.html' %}
{% block content %}

    <div class="w-full h-[70vh] min-h-96 bg-no-repeat bg-cover bg-center bg-[url('/static/images/hero.jpg')]">
        <div class="bg-black/50 backdrop-blur-sm h-full content-center md:content-end text-center md:text-start">
            <div class="content-container padded mx-auto w-full">
                <h1 class="title text-white mb-2">Beacon</h1>
                <p class="h1-small font-light text-neutral-100 mb-6">Connecting your with your healthcare provider.</p>
                <a href="{{ url_for('core.dashboard') }}" class="button-lg button-blue">View Dashboard</a>
            </div>
        </div>
    </div>

    <div class="bg-color-accent">
        <div class="content-container padded">
            <h2 class="h2 text-color-dark">Call Us Now</h2>
            <p class="body text-color-dark-2">Need to speak with someone? Call us now at <a href="tel:+12295979512">(229)
                597-9512</a>.</p>
        </div>
    </div>

    <div class="content-container padded grid grid-col-1 md:grid-cols-3 gap-4">
        <div class="mb-3">
            <h2 class="h2 text-color-dark">How We Help</h2>
        </div>
        <div class="basis-full md:col-span-2 space-y-4">

            <div class="md:flex md:flex-row md:justify-between md:gap-4 pb-4 border-b border-color">
                <h3 class="h3-small text-color-dark basis-1/4">Personalized Care</h3>
                <div class="basis-3/4">
                    <p class="body text-color-dark-2">
                        Our platform connects you with your doctors, providing personalized care tailored to your needs.
                    </p>
                </div>
            </div>

            <div class="md:flex md:flex-row md:justify-between md:gap-4 pb-4 border-b border-color">
                <h3 class="h3-small text-color-dark basis-1/4">Quick Communication</h3>
                <div class="basis-3/4">
                    <p class="body text-color-dark-2">
                        Quickly get in touch with your doctors via web chat or phone calls.
                    </p>
                </div>
            </div>

            <div class="md:flex md:flex-row md:justify-between md:gap-4 pb-4 border-b border-color">
                <h3 class="h3-small text-color-dark basis-1/4">Secure Messaging</h3>
                <div class="basis-3/4">
                    <p class="body text-color-dark-2">
                        Communicate securely with your healthcare providers through our messaging system.
                    </p>
                </div>
            </div>


        </div>
    </div>

{% endblock %}